config/routes.rb
Rails.application.routes.draw do

  # Add static pages
  get "/pages/*page" => "pages#show", as: "pages"
  
  resources :presentations, except: [:index] do
    resources :parts
    # module: lets us have /presentations/likes/likes_controller.rb
    resource :like, module: :presentations
  end

  # Use another controller to override redirects
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]
  # Define another route for logged in users
  # authenticated :user do
  #   root "pages#home"
  # end

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :presentation
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :presentation
end

app/models/presentation.rb
class Presentation < ApplicationRecord
  validates :title, presence: true
  belongs_to :user, default: -> { Current.user }
  has_many :parts, dependent: :destroy
  has_many :likes
  has_one_attached :cover
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :nickname, presence:true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  
  has_many :presentations
  has_many :likes
  
  has_one_attached :avatar

  def likes?(presentation)
    presentation.likes.where(user_id: id).any?
  end

  def avatar_url
    hash = Digest::MD5.hexdigest(email)
    "http://www.gravatar.com/avatar/#{hash}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :set_current_user

  private

    # This cant be in registrations_controller for some reason
    def after_sign_out_path_for(resource)
      new_user_session_path
    end

    # Current user available "globally"
    def set_current_user
      Current.user = current_user
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_users
  
  def home
    @users = User.all
  end

  def show
    if valid_page?
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
    def valid_page?
      File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
    end

    def set_users
      @users = User.all
    end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_presentation
  before_action :set_part, except: [:new, :create]

  def show
  end

  def new
    @part = Part.new
  end

  def edit
    
  end

  def create
    @presentation.parts.create(parts_params)
    redirect_to @presentation, notice: "New Part Created!"
  end

  def update
    if @part.update(parts_params)
      redirect_to @presentation, notice: "Updated Succesfully!"
    else
      render :show, notice: "There was an error updating the part"
    end
    
  end

  def destroy
    @part.destroy
    title = @part.title

    if @part.destroy
      redirect_to @presentation, notice: "#{title} was deleted succesfully"
    else
      render :show, notice: "There was an error deleting the part"
    end

  end

  private
    def set_presentation
      @presentation = Presentation.find(params[:presentation_id])
      
    end

    def set_part
      @part = Part.find(params[:id])
      authorize @presentation
    end

    def parts_params
      params.required(:part).permit(:title, :id, :body)
    end
end

app/controllers/presentations/likes_controller.rb
class Presentations::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_presentation

  def create
    @presentation.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to @presentation }
      format.js
    end
  end

  def destroy
    @presentation.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to @presentation }
      format.js
    end
  end
  
  private
    def set_presentation
      @presentation = Presentation.find(params[:presentation_id])
    end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
    
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)
    authorize @presentation
    respond_to do |format|
      if @presentation.save
        format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
      authorize @presentation
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:title, :user_id, :cover)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  def index
  end

  def create
    super
    if @user.persisted?
      UserMailer.with(user: @user).welcome_email.deliver_later
    end
  end

  def after_sign_in_path_for(resource)
    presentations_path
  end

  def after_sign_up_path_for(resource)
    presentations_path
  end

  def after_update_path_for(resource)
    presentations_path
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar, :nickname])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @presentations = @user.presentations.all
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand">
  <div class="container-fluid">
    
    <%= link_to "Preze", pages_path("home"), :class=> 'navbar-brand' %>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to 'Create', new_presentation_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "My Prezes", user_path(current_user), class: "nav-link" %></li>
        <li class="nav-item">
          <%= link_to(edit_user_registration_path, :class => "nav-link") do %>
            <% if Current.user.avatar.attached? %>
              <%= image_tag current_user.avatar.variant(resize: "20x20") %>
            <% else %>
              <%= image_tag current_user.avatar_url, width: 20 %>
            <% end %>
            <%= Current.user.nickname %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, :class => 'nav-link' %></li>
        <li class="nav-item"><%= link_to "Login", new_user_session_path, :class => 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slide</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/themes/beagle.min.css" type="text/css" media="screen" charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,900" rel="stylesheet">
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'app' %>
  </head>

  <body>
  
    <%= render 'layouts/nav' %>
    <% if notice.present? %>
      <div class="alert alert-info"><%= notice %></div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-warning"><%= alert %></div>
    <% end %>
    <div class="site-wrapper">
      <div class="container-fluid">
        <%= yield %>
      </div>
    </div>
    <script>
      var editor = new MediumEditor('.editable', {
        // options go here
      });
    </script>
  </body>

   

</html>

app/views/pages/bye.html.erb
bye

app/views/pages/home.html.erb
<h1>Prezes</h1>

<% @users.each do |user| %>
  <div class="users mb-4">
  <% if user.nickname.present? %>
      <% if user.avatar.attached? %>
        <%= image_tag user.avatar.variant(resize: "20x20") %>
      <% else %>
        <%= image_tag user.avatar_url, width: 20 %>
      <% end %>
      <h3><%= link_to user.nickname, user_path(user.id) %></h3>
  <% end %>
  </div>
<% end %>

app/views/pages/index.html.erb
welcome what is this?

<% @Users.each do |user| %>
  <%= user.nickname %>
<% end %>

app/views/parts/_form.html.erb
<%= simple_form_for [ @presentation, @part ] do |form| %>
  <%= form.text_field :title, class: "title-control mb-2", placeholder: "Enter your title" %>
  <%= form.text_area :body, class: "editable" %>
  <%= form.button :submit, class: "btn-success" %>
<% end %>

app/views/parts/_part.html.erb
<div class="card mb-2">
  <div class="card-body">
    <h3><%= part.title %></h3>
    <%= part.body.html_safe %>
    <% if policy(@presentation).edit? %>
    <%= link_to 'Edit', edit_presentation_part_path(@presentation, part) %>
    <% end %>
  </div>
</div>

app/views/parts/edit.html.erb
<%= render 'form' %>

<%= link_to 'Destroy', [@presentation, @part], method: :delete, confirm: "Are your sure?" %>

app/views/parts/new.html.erb
<%= render 'form' %>

app/views/presentations/_form.html.erb
<%= simple_form_for @presentation, local: true do |form| %>

  <%= form.input :title %>

  <% if presentation.cover.attached? %>
    <%= image_tag presentation.cover.variant(resize: "250x250") %>
  <% end %>
  <%= form.input :cover, direct_upload: true, as: :file %>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/presentations/_likes.html.erb
<% if user_signed_in? && current_user.likes?(presentation)%>
  <%= link_to "Unlike", presentation_like_path(presentation), method: :delete, remote: true %>
<% elsif user_signed_in? %>
  <%= link_to "like", presentation_like_path(presentation), method: :post, remote: true %>
<% else %>
  <%= link_to "like", presentation_like_path(presentation), method: :post %>
<% end %>

<%= presentation.likes.count %>

<% presentation.likes.each do |like| %>
  <%= image_tag like.user.avatar_url, width: 20 %>
<% end %>

app/views/presentations/_presentation.html.erb
<div class="card">
  <% if presentation.cover.attached? %>
    <%= image_tag presentation.cover.variant(resize: "250x250"), class: "card-img-top" %>
  <% end %>
  <div class="card-body">
    <h3><%= link_to presentation.title, presentation %></h3>
    
    <div class="<%= dom_id(presentation) %>-likes">
      <%= render partial: "presentations/likes", locals: { presentation: presentation } %>
    </div>
  </div>
</div>

app/views/presentations/edit.html.erb
<h5>Editing Presentation</h5>

<%= render 'form', presentation: @presentation %>

<%= link_to 'Destroy', @presentation, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Show', @presentation %> |
<%= link_to 'Back', presentations_path %>

app/views/presentations/index.html.erb
<h1>Presentations</h1>
<%= link_to 'New Presentation', new_presentation_path %>

<div class="grid mt-2">
  <% if @presentations.any? %>
    <%= render @presentations %>
  <% else %>
    <td>Nope</td>
  <% end %>
</div>

app/views/presentations/likes/create.js.erb
var ele = document.querySelector(".<%= dom_id(@presentation) %>-likes")
ele.innerHTML = "<%=j render partial: 'presentations/likes', locals: { presentation: @presentation } %>"

app/views/presentations/likes/destroy.js.erb
var ele = document.querySelector(".<%= dom_id(@presentation) %>-likes")
ele.innerHTML = "<%=j render partial: 'presentations/likes', locals: { presentation: @presentation } %>"

app/views/presentations/new.html.erb
<h1>New Preze</h1>

<%= render 'form', presentation: @presentation %>

app/views/presentations/show.html.erb
<% if @presentation.cover.attached? %>
  <%= image_tag @presentation.cover.variant(resize: "250x250"), class: "card-img-top" %>
<% end %>

<h1><%= @presentation.title %></h1>

<div class="<%= dom_id(@presentation) %>-likes">
  <%= render partial: "presentations/likes", locals: { presentation: @presentation } %>
</div>

<% if policy(@presentation).edit? %>
  <%= link_to 'Edit', edit_presentation_path(@presentation), class: "btn btn-primary" %>
<% end %>

<h3>Parts</h3>

<% if policy(@presentation).edit? %>
  <%= link_to "Create part", new_presentation_part_path(@presentation, @part) %>
<% end %>

<div class="parts mt-2">
  <% if @presentation.parts.any? %>
    <%= render @presentation.parts %>
  <% else %>
    no parts
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Prezes by <%= @user.nickname %></h1>

<div class="grid mt-2">
  <%= render @user.presentations %>
</div>